name: Build and deployment

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build and deployment
    runs-on: ubuntu-latest
    steps:
    - name: git pull with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          git pull
          
    - name: build with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          go build -o ${{ secrets.SERVICE_NAME }}
    
    
    - name: kill with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: false
        script: |
        #  sudo pkill ${{ secrets.SERVICE_NAME }}
          
    
    
    - name: run with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          sudo nohup ~/echo-dev.sh
