name: Build and deployment

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and deployment
    runs-on: ubuntu-latest
    steps:
    - name: git pull with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          git reset --hard
          git pull


    - name: test with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          go get
          go test ./... -configFilePath="../config/echo-dev.toml"


    - name: build with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          go get
          go build
    
    
    - name: kill with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: false
        script: |
          sudo pkill myapp
          
    
    
    - name: run with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          sudo nohup ./myapp -configFilePath="./config/echo-dev.toml" > /dev/null &
