name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: build with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd ~/echo
          git pull
          go build -o ${{ secrets.SERVICE_NAME }}
          
            
    - name: kill with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          pkill -ef ${{ secrets.SERVICE_NAME }}

    - name: run with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          nohup ~/echo/${{ secrets.SERVICE_NAME }} ${{ secrets.DB_HOST }} ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_DBNAME }} ${{ secrets.DB_PORT }} > ~/log/${{ secrets.SERVICE_NAME }}.$(date --iso).out &
