name: Go develop deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cehckout source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
      uses: appleboy/ssh-action@v0.1.4
      with:
        # ssh host
        host: ${{ secrets.HOST }}
        # ssh port
        port: ${{ secrets.PORT }}
        # ssh username
        username: ${{ secrets.USERNAME }}
        # ssh password
        password: ${{ secrets.PASSWORD }}
        # synchronous execution if multiple hosts
